-- CreateTable
CREATE TABLE "Cliente2" (
    "id" SERIAL NOT NULL,
    "RucE" TEXT NOT NULL,
    "Cd_Clt" TEXT NOT NULL,
    "Cd_TDI" TEXT NOT NULL,
    "NDoc" TEXT,
    "RSocial" TEXT,
    "ApPat" TEXT,
    "ApMat" TEXT,
    "Nom" TEXT,
    "Cd_Pais" TEXT,
    "CodPost" TEXT,
    "Ubigeo" TEXT,
    "Direc" TEXT,
    "Telf1" TEXT,
    "Telf2" TEXT,
    "Fax" TEXT,
    "Correo" TEXT,
    "PWeb" TEXT,
    "Obs" TEXT,
    "CtaCtb" TEXT,
    "DiasCbr" TEXT,
    "PerCbr" TEXT,
    "CtaCte" TEXT,
    "Cd_CGC" TEXT,
    "Estado" BOOLEAN,
    "CA01" TEXT,
    "CA02" TEXT,
    "CA03" TEXT,
    "CA04" TEXT,
    "CA05" TEXT,
    "CA06" TEXT,
    "CA07" TEXT,
    "CA08" TEXT,
    "CA09" TEXT,
    "CA10" TEXT,
    "Cd_Aux" TEXT,
    "Cd_TClt" TEXT,
    "FecReg" TIMESTAMP(3),
    "UsuCrea" TEXT,
    "FecMdf" TIMESTAMP(3),
    "UsuMdf" TEXT,
    "NComercial" TEXT,
    "IB_AgRet" BOOLEAN,
    "IB_AgPercep" BOOLEAN,
    "IB_BuenContrib" BOOLEAN,
    "Cd_Vdr" TEXT,
    "SaldoAFavor" DECIMAL(65,30),
    "Msj_Alert" TEXT,
    "EsExtranjero" BOOLEAN,
    "EnvioDocVtaAuto" BOOLEAN,
    "EnvioDocVtaAdjto" BOOLEAN,
    "PassWeb" TEXT,
    "DefinirDiasCredito" BOOLEAN,
    "CodEAN" TEXT,
    "C_CD_CC" TEXT,
    "IB_ConsumidorFinal" BOOLEAN,
    "C_FEC_GEN_PASS" TIMESTAMP(3),
    "C_USU_GEN_PASS" TEXT,
    "C_CORREO_ENV_PASS" TEXT,
    "C_FORMACOBRO" TEXT,
    "C_DIASCOBRO" INTEGER,
    "C_IB_PAGO_DESTINO" BOOLEAN,
    "C_ESTADO_LINEA_CREDITO" BOOLEAN,
    "C_FEC_AMPLIACION_LINEA_CRED" TIMESTAMP(3),
    "C_MOTIVO_AMPLIACION_LINEA_CRED" TEXT,
    "C_IB_AGENTE" BOOLEAN,
    "C_CD_CCOSTOS" TEXT,
    "C_CD_SCCOSTOS" TEXT,
    "C_CD_SSCCOSTOS" TEXT,
    "C_DIAS_TOLERANCIA_CREDITO" INTEGER,
    "C_FECHA_INGRESO" TIMESTAMP(3),
    "C_CODIGO_HOMOLOGACION" TEXT,
    "C_IB_MULTIEMPRESA" BOOLEAN,
    "C_URBANIZACION" TEXT,

    CONSTRAINT "Cliente2_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Cliente2_Cd_Clt_key" ON "Cliente2"("Cd_Clt");
