-- AlterTable
ALTER TABLE "TicketInfo" ALTER COLUMN "C_TIP_DOC_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_UBIGEO_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_DIRECCION_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_DEPARTAMENTO_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_PROVINCIA_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_DISTRITO_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_NOMBRE_COMERCIAL_EMISOR" DROP NOT NULL,
ALTER COLUMN "C_TIP_DOC" DROP NOT NULL,
ALTER COLUMN "C_NRO_DOC_ADQUIRIENTE" DROP NOT NULL,
ALTER COLUMN "C_APAMINO_RAZON_SOCIAL_ADQUIRIENTE" DROP NOT NULL,
ALTER COLUMN "C_MONTO_TOTAL_PERCEP" DROP NOT NULL,
ALTER COLUMN "C_LEYENDA" DROP NOT NULL,
ALTER COLUMN "C_TIP_DOC_ADQUIRIENTE" DROP NOT NULL;
