-- CreateTable
CREATE TABLE "Service2" (
    "id" SERIAL NOT NULL,
    "RucE" TEXT,
    "Cd_Srv" TEXT,
    "CodCo" TEXT,
    "Nombre" TEXT,
    "Descrip" TEXT,
    "NCoto" TEXT,
    "Cta1" TEXT,
    "Cta2" TEXT,
    "Img" TEXT,
    "Cd_GS" TEXT,
    "Cd_CGP" TEXT,
    "Cd_CC" TEXT,
    "Cd_SC" TEXT,
    "Cd_SS" TEXT,
    "IC_TipServ" TEXT,
    "UsuCrea" TEXT,
    "UsuMdf" TEXT,
    "FecReg" TIMESTAMP(3) NOT NULL,
    "FecMdf" TIMESTAMP(3) NOT NULL,
    "Estado" TEXT,
    "CA01" TEXT,
    "CA02" TEXT,
    "CA03" TEXT,
    "CA04" TEXT,
    "CA05" TEXT,
    "CA06" TEXT,
    "CA07" TEXT,
    "CA08" TEXT,
    "CA09" TEXT,
    "CA10" TEXT,
    "Cta3" TEXT,
    "Cta4" TEXT,
    "Cta5" TEXT,
    "Cta6" TEXT,
    "Cta7" TEXT,
    "Cta8" TEXT,
    "IB_LF" TEXT,
    "IB_ActivoFijo" TEXT,
    "Cta9" TEXT,
    "Cta10" TEXT,
    "Cta11" TEXT,
    "Cta12" TEXT,
    "C_IB_LC" TEXT,
    "C_CD_SRV_INAFECTO" TEXT,
    "C_CD_SRV_AFECTO" TEXT,
    "C_IB_SOBRE_TASA" TEXT,
    "C_COD_BBSS" TEXT,
    "C_CD_SERV_ADICIONAL" TEXT,
    "C_PORCENTAJE_AFECTADO" TEXT,
    "C_IB_ES_OBLIGATORIO" TEXT,
    "C_IB_INCLUYE_IGV" TEXT,
    "C_IB_CRM" TEXT,
    "C_CODIGO_HOMOLOGACION" TEXT,
    "C_IB_MULTIEMPRESA" TEXT,

    CONSTRAINT "Service2_pkey" PRIMARY KEY ("id")
);
