-- CreateTable
CREATE TABLE "TicketInfo" (
    "id" SERIAL NOT NULL,
    "C_ID" INTEGER NOT NULL,
    "C_FEC_ED" TIMESTAMP(3) NOT NULL,
    "C_TIP_DOC_EMISOR" TEXT NOT NULL,
    "C_APAMNO_RAZON_SOCIAL_EMISOR" TEXT NOT NULL,
    "C_UBIGEO_EMISOR" TEXT NOT NULL,
    "C_DIRECCION_EMISOR" TEXT NOT NULL,
    "C_DEPARTAMENTO_EMISOR" TEXT NOT NULL,
    "C_PROVINCIA_EMISOR" TEXT NOT NULL,
    "C_DISTRITO_EMISOR" TEXT NOT NULL,
    "C_NOMBRE_COMERCIAL_EMISOR" TEXT NOT NULL,
    "C_TIP_DOC" TEXT NOT NULL,
    "C_NRO_SERIE" TEXT NOT NULL,
    "C_NRO_DOC" TEXT NOT NULL,
    "C_NRO_DOC_ADQUIRIENTE" TEXT NOT NULL,
    "C_APAMINO_RAZON_SOCIAL_ADQUIRIENTE" TEXT NOT NULL,
    "C_MONEDA" TEXT NOT NULL,
    "C_MONTO_TOTAL_IGV" INTEGER NOT NULL,
    "C_MONTO_PAGAR" INTEGER NOT NULL,
    "C_MONTO_TOTAL_PERCEP" INTEGER NOT NULL,
    "C_LEYENDA" TEXT NOT NULL,
    "C_FEC_CREA_FACE" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TicketInfo_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TicketInfoDetail" (
    "id" SERIAL NOT NULL,
    "C_ID" INTEGER NOT NULL,
    "C_ID_ITEM" TEXT NOT NULL,
    "C_DESCRIP_ITEM" TEXT NOT NULL,
    "C_VALOR_VENTA_UNITARIA" INTEGER NOT NULL,
    "C_CANTIDAD_ITEM" INTEGER NOT NULL,
    "C_IGV_TOTAL_ITEM" INTEGER NOT NULL,
    "C_COD_SUNAT_PROD_SERV_ITEM" TEXT NOT NULL,

    CONSTRAINT "TicketInfoDetail_pkey" PRIMARY KEY ("id")
);
